Feature/url model
IEEE-VIT/flask.ly pull request #11
Opened 2020-10-01 13:55 UTC by andrewmiko

I've finished Url model feature development.

Several features were added:

- New requirements: Flask Sqlalchemy, Sqlalchemy, environs, pylint
- New model for Url
- New App file structure with db init functionality

This merge is very important to have **BEROFE** all other works with database, models or app logic.

@ShubhamPalriwala please verify and add your comments.

2020-10-01 18:15 UTC, ShubhamPalriwala commented on models.py
> +    created_at = db.Column(db.DateTime, default=dt.datetime.now)
You can make the `original url` as the primary key so that we dont need an `id` field.
You can eliminate the `created_at` field too.

2020-10-01 18:28 UTC, aryan9600 requested changes

2020-10-01 18:28 UTC, aryan9600 commented on models.py
> +    created_at = db.Column(db.DateTime, default=dt.datetime.now)
No let's have an `id` field, but the `original_url` should be unique too imo @andrewmiko

2020-10-01 18:28 UTC, aryan9600 commented on .env.template
> +SQLALCHEMY_DATABASE_NAME = "db.sqlite3"
Since we're add support for `.env`, we should also be updating the README's [Getting Started](https://github.com/IEEE-VIT/flask.ly#getting-started) section with steps about the same.

2020-10-01 19:12 UTC, andrewmiko commented on .env.template
> +SQLALCHEMY_DATABASE_NAME = "db.sqlite3"
@aryan9600 I've added new information about `.env` file. Please check updated PR.

2020-10-02 10:54 UTC, andrewmiko commented
@aryan9600 @ShubhamPalriwala please review updated PR. Cheers.

2020-10-06 17:23 UTC, merged